setwd("~/Dropbox/ripley/Analytics/DB2/recomendacioncompras")
library(arules)
library(RJDBC)
library(ggplot2)
library(RMySQL)
jcc = JDBC("com.ibm.db2.jcc.DB2Driver","~/Dropbox/Ripley/Analytics/DB2/db2driver/db2jcc4.jar")

conn = dbConnect(jcc,
                 "jdbc:db2://10.0.156.20:50000/MALL:currentSchema=DB2INST1;",
                 #currentSchema="DB2INST1",
                 user="consulta",
                 password="consulta")

rs = dbSendQuery(conn,
                 "SELECT DB2INST1.ORDERITEMS.PARTNUM, DB2INST1.ORDERITEMS.ORDERS_ID, DB2INST1.ORDERS.MEMBER_ID
                 FROM DB2INST1.ORDERS
                 JOIN DB2INST1.ORDERITEMS 
                 ON DB2INST1.ORDERS.ORDERS_ID = DB2INST1.ORDERITEMS.ORDERS_ID
                 WHERE (DB2INST1.ORDERS.STATUS='C' OR DB2INST1.ORDERS.STATUS='G')
                 AND DB2INST1.ORDERS.TIMEPLACED > '2015-07-07 23:30:11'")
ORDERS = fetch(rs, -1)
#ORDERSTEMP <- ORDERS
#save(ORDERSTEMP,file="ORDERSTEM.RDA")
#load(file="ORDERSTEM.RDA")
#ORDERS <- ORDERSTEMP
ORDERS <- subset(ORDERS,select=c("ORDERS_ID","PARTNUM"))

rs = dbSendQuery(conn,
                 "WITH TEMP_RET AS (SELECT HIJO.CATENTRY_ID,
                 CASE WHEN MAX(DECODE(HIJO_ATTR.IDENTIFIER, 'RETIRO_TIENDA', HIJO_ATTR.IDENTIFIER )) = 'RETIRO_TIENDA' THEN 'SI' ELSE 'NO' END AS RET_HIJO,
                 CASE WHEN MAX(DECODE(HIJO_ATTR.IDENTIFIER, 'DESP_DOMICILIO', HIJO_ATTR.IDENTIFIER )) = 'DESP_DOMICILIO' THEN 'SI' ELSE 'NO' END AS DESP_HIJO,
                 CASE WHEN MAX(DECODE(HIJO_ATTR.IDENTIFIER, 'RETIRO_CITY_BOX', HIJO_ATTR.IDENTIFIER )) = 'RETIRO_CITY_BOX' THEN 'SI' ELSE 'NO' END AS RR_HIJO,
                 
                 CASE WHEN MAX(DECODE(PADRE_ATTR.IDENTIFIER, 'RETIRO_TIENDA', PADRE_ATTR.IDENTIFIER )) = 'RETIRO_TIENDA' THEN 'SI' ELSE 'NO' END AS RET_PADRE,
                 CASE WHEN MAX(DECODE(PADRE_ATTR.IDENTIFIER, 'DESP_DOMICILIO', PADRE_ATTR.IDENTIFIER )) = 'DESP_DOMICILIO' THEN 'SI' ELSE 'NO' END AS DESP_PADRE,
                 CASE WHEN MAX(DECODE(PADRE_ATTR.IDENTIFIER, 'RETIRO_CITY_BOX', PADRE_ATTR.IDENTIFIER )) = 'RETIRO_CITY_BOX' THEN 'SI' ELSE 'NO' END AS RR_PADRE
                 
                 FROM CATENTRY AS HIJO
                 JOIN CATENTREL ON (CATENTREL.CATENTRY_ID_CHILD = HIJO.CATENTRY_ID)
                 JOIN CATENTRY AS PADRE ON (PADRE.CATENTRY_ID = CATENTREL.CATENTRY_ID_PARENT)
                 
                 LEFT OUTER JOIN CATENTRYATTR AS HIJO_CATENTRYATTR ON (HIJO_CATENTRYATTR.CATENTRY_ID = HIJO.CATENTRY_ID)
                 LEFT OUTER JOIN ATTR AS HIJO_ATTR ON (HIJO_ATTR.ATTR_ID = HIJO_CATENTRYATTR.ATTR_ID)
                 LEFT OUTER JOIN ATTRVAL AS HIJO_ATTRVAL ON (HIJO_ATTRVAL.ATTRVAL_ID = HIJO_CATENTRYATTR.ATTRVAL_ID)
                 LEFT OUTER JOIN ATTRDESC AS HIJO_ATTRDESC ON (HIJO_ATTRDESC.ATTR_ID = HIJO_ATTR.ATTR_ID)
                 LEFT OUTER JOIN ATTRVALDESC AS HIJO_ATTRVALDESC ON (HIJO_ATTRVALDESC.ATTRVAL_ID = HIJO_ATTRVAL.ATTRVAL_ID)
                 
                 LEFT OUTER JOIN CATENTRYATTR AS PADRE_CATENTRYATTR ON (PADRE_CATENTRYATTR.CATENTRY_ID = PADRE.CATENTRY_ID)
                 LEFT OUTER JOIN ATTR AS PADRE_ATTR ON (PADRE_ATTR.ATTR_ID = PADRE_CATENTRYATTR.ATTR_ID)
                 LEFT OUTER JOIN ATTRVAL AS PADRE_ATTRVAL ON (PADRE_ATTRVAL.ATTRVAL_ID = PADRE_CATENTRYATTR.ATTRVAL_ID)
                 LEFT OUTER JOIN ATTRDESC AS PADRE_ATTRDESC ON (PADRE_ATTRDESC.ATTR_ID = PADRE_ATTR.ATTR_ID)
                 LEFT OUTER JOIN ATTRVALDESC AS PADRE_ATTRVALDESC ON (PADRE_ATTRVALDESC.ATTRVAL_ID = PADRE_ATTRVAL.ATTRVAL_ID)
                 WHERE CATENTREL.CATRELTYPE_ID = 'PRODUCT_ITEM'
                 GROUP BY HIJO.CATENTRY_ID)
                 
                 , TEMP_CAT_VTA_HIJO AS (SELECT DISTINCT HIJO.CATENTRY_ID,
                 1 AS CATALOGO_VENTA_HIJO
                 
                 FROM CATENTRY AS HIJO
                 JOIN CATGPENREL AS HIJO_CATGPENREL ON (HIJO_CATGPENREL.CATENTRY_ID = HIJO.CATENTRY_ID)
                 WHERE HIJO_CATGPENREL.CATALOG_ID = 10051)
                 
                 , TEMP_CAT_VTA_PADRE AS (SELECT DISTINCT HIJO.CATENTRY_ID,
                 1 AS CATALOGO_VENTA_PADRE,
                 LISTAGG(CATGROUP.IDENTIFIER, ' | ') AS ID_CATEGORIAS_VENTA_PADRE
                 FROM CATENTRY AS HIJO
                 JOIN CATENTREL ON (CATENTREL.CATENTRY_ID_CHILD = HIJO.CATENTRY_ID)
                 JOIN CATENTRY AS PADRE ON (PADRE.CATENTRY_ID = CATENTREL.CATENTRY_ID_PARENT)
                 JOIN CATGPENREL ON (CATGPENREL.CATENTRY_ID = PADRE.CATENTRY_ID AND CATGPENREL.CATALOG_ID = '10051')
                 JOIN CATGROUP ON (CATGROUP.CATGROUP_ID = CATGPENREL.CATGROUP_ID)
                 JOIN CATGRPDESC ON (CATGROUP.CATGROUP_ID = CATGRPDESC.CATGROUP_ID)
                 JOIN CATGPENREL AS CATGPENREL2 ON (CATGPENREL2.CATENTRY_ID = PADRE.CATENTRY_ID AND CATGPENREL2.CATALOG_ID = '10001')
                 JOIN CATGRPREL ON (CATGPENREL2.CATGROUP_ID = CATGRPREL.CATGROUP_ID_CHILD)
                 JOIN CATGROUP AS CATGROUP2 ON (CATGROUP2.CATGROUP_ID = CATGRPREL.CATGROUP_ID_PARENT)
                 GROUP BY HIJO.CATENTRY_ID)
                 
                 , TEMP_STOCK AS (SELECT CATENTRY.CATENTRY_ID,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010039', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_REDEX_39,
                 
                 CASE WHEN SUM(INVSTFFMVW.QTYAVAILABLE)-COALESCE(MAX(DECODE(FFMCENTER.NAME, '010039', INVSTFFMVW.QTYAVAILABLE)),0) > 0 THEN 'SI'
                 ELSE 'NO'
                 END AS STOCK_TIENDAS,
                 
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010012', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PARQUE_ARAUCO_12,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010034', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_COSTANERA_34,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010016', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PLAZA_VESPUCIO_16,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010045', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PLAZA_OESTE_45,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010025', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_VALPARAISO_25,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010041', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_SERENA_41,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010032', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_RANCAGUA_32,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010074', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_TALCA_74,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010076', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_CURICO_76,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010014', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PTO_MONTT_14,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010057', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_FLORIDA_CENTER_57,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010077', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_LA_DEHESA_77,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010088', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_ARAUCO_MAIPU_88,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010048', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PLAZA_NORTE_48,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010071', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PLAZA_EGANA_71,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010037', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_MARINA_37,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010028', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_EL_TREBOL_28,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010000', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_HUERFANOS_00,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010002', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_MALL_CONCEPCION_02,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010003', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_VINA_03,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010004', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_TEMUCO_04,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010010', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_LOS_ANDES_10,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010018', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PUENTE_18,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010022', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_CHILLAN_22,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010026', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_ANTOFAGASTA_26,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010029', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_ALTO_LAS_CONDES_29,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010046', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_TOBALABA_46,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010049', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_IQUIQUE_49,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010051', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_MALL_CALAMA_51,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010068', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PORTAL_TEMUCO_68,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010078', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PTO_MONTT_II_78,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010079', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_LA_CALERA_79,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010084', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_COPIAPO_84,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010096', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_PUENTA_ARENAS_96,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010097', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_NVA_ALAMEDA_97,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010098', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_NVA_VALDIVIA_STORE_98,
                 COALESCE(MAX(DECODE(FFMCENTER.NAME, '010099', INVSTFFMVW.QTYAVAILABLE)),0) AS STOCK_SAN_BERNARDO_99
                 FROM CATENTRY
                 JOIN INVSTFFMVW ON (INVSTFFMVW.ITEMSPC_ID = CATENTRY.ITEMSPC_ID)
                 JOIN FFMCENTER ON (FFMCENTER.FFMCENTER_ID = INVSTFFMVW.FFMCENTER_ID)
                 WHERE FFMCENTER.NAME <> 'ripleycl'
                 GROUP BY CATENTRY.CATENTRY_ID)
                 
                 , TEMP_PRECIOS AS(select hijo.PARTNUMBER AS PARTNUMBER,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'ListPrice Vigente', price_hijo.PRICE)),-1) 
                 AS PRECIO_VIGENTE,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'ListPrice Master', price_hijo.PRICE)),-1)
                 AS PRECIO_MASTER,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'ListPrice Costo', price_hijo.PRICE)),-1) 
                 AS PRECIO_COSTO,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'MC - Precios Especiales TMP', price_hijo.PRICE)),-1)
                 AS PRECIO_OFERTA_TMP,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'MC - Lista Flag TMP', price_hijo.PRICE)),-1) 
                 AS FLAG_OFERTA_TMP,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'MC - Precios Especiales CAR', price_hijo.PRICE)),-1) 
                 AS PRECIO_RIPLEY_CAR,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'MC - Lista Flag CAR', price_hijo.PRICE)),-1)
                 AS FLAG_RIPLEY_CAR,
                 COALESCE(MAX(DECODE(trade_hijo.NAME, 'MC - FlagBajo Costo', price_hijo.PRICE)),-1)
                 AS FLAG_BAJO_COSTO
                 from CATENTRY AS hijo
                 JOIN OFFER AS offer_hijo ON (offer_hijo.CATENTRY_ID = hijo.CATENTRY_ID) 
                 JOIN TRADEPOSCN AS trade_hijo ON (offer_hijo.TRADEPOSCN_ID = trade_hijo.TRADEPOSCN_ID) 
                 JOIN OFFERPRICE AS price_hijo ON (price_hijo.OFFER_ID = offer_hijo.OFFER_ID)
                 WHERE offer_hijo.PUBLISHED = 1
                 GROUP BY hijo.PARTNUMBER)
                 
                 , TEMP_CAT_MAESTRO_HIJO AS(SELECT HIJO.CATENTRY_ID
                 , 1 AS HIJO_CAT_MAESTRO
                 FROM CATENTRY AS HIJO
                 JOIN CATGPENREL AS MAESTRO_CATGPENREL ON (MAESTRO_CATGPENREL.CATENTRY_ID = HIJO.CATENTRY_ID AND MAESTRO_CATGPENREL.CATALOG_ID = '10001'))
                 
                 , TEMP_ATTR_DEFINICION AS (SELECT HIJO.CATENTRY_ID,
                 LISTAGG (HIJO_ATTRDESC.NAME, '/') || ' : ' || LISTAGG (HIJO_ATTRVALDESC.VALUE, '/') AS ATRIBUTOS_DEFINICION
                 FROM CATENTRY AS HIJO
                 JOIN CATENTRYATTR AS HIJO_CATENTRYATTR ON (HIJO_CATENTRYATTR.CATENTRY_ID = HIJO.CATENTRY_ID and HIJO_CATENTRYATTR.USAGE = 1)
                 LEFT OUTER JOIN ATTR AS HIJO_ATTR ON (HIJO_ATTR.ATTR_ID = HIJO_CATENTRYATTR.ATTR_ID)
                 LEFT OUTER JOIN ATTRVAL AS HIJO_ATTRVAL ON (HIJO_ATTRVAL.ATTRVAL_ID = HIJO_CATENTRYATTR.ATTRVAL_ID)
                 LEFT OUTER JOIN ATTRDESC AS HIJO_ATTRDESC ON (HIJO_ATTRDESC.ATTR_ID = HIJO_ATTR.ATTR_ID)
                 LEFT OUTER JOIN ATTRVALDESC AS HIJO_ATTRVALDESC ON (HIJO_ATTRVALDESC.ATTRVAL_ID = HIJO_ATTRVAL.ATTRVAL_ID)
                 WHERE HIJO.CATENTTYPE_ID = 'ItemBean'
                 GROUP BY HIJO.CATENTRY_ID)
                 
                 SELECT
                 MAESTRO_CATGRPDESC.NAME AS CATALOGO_MAESTRO_NAME
                 , MAESTRO_CATGROUP2.IDENTIFIER AS CATALOGO_MAESTRO2_IDENTIFIER
                 , PADRE.PARTNUMBER AS SKU_PADRE
                 , PADRE_CATENTDESC.NAME AS NOMBRE_PADRE
                 , PADRE.MFNAME AS MARCA_PADRE
                 , HIJO.PARTNUMBER AS SKU_HIJO
                 , CASE WHEN PRECIOS_HIJO.PRECIO_VIGENTE > -1 THEN PRECIOS_HIJO.PRECIO_VIGENTE ELSE PRECIOS_PADRE.PRECIO_VIGENTE END AS PRECIO_VIGENTE
                 , CASE WHEN PRECIOS_HIJO.PRECIO_MASTER > -1 THEN PRECIOS_HIJO.PRECIO_MASTER ELSE PRECIOS_PADRE.PRECIO_MASTER END AS PRECIO_MASTER
                 , CASE WHEN PRECIOS_HIJO.PRECIO_COSTO > -1 THEN PRECIOS_HIJO.PRECIO_COSTO ELSE PRECIOS_PADRE.PRECIO_COSTO END AS PRECIO_COSTO
                 , HIJO_CATENTDESC.FULLIMAGE
                 FROM CATENTRY AS HIJO
                 JOIN CATENTDESC AS HIJO_CATENTDESC ON (HIJO_CATENTDESC.CATENTRY_ID = HIJO.CATENTRY_ID AND HIJO_CATENTDESC.LANGUAGE_ID = '-5')
                 JOIN CATENTREL ON (CATENTREL.CATENTRY_ID_CHILD = HIJO.CATENTRY_ID)
                 JOIN CATENTRY AS PADRE ON (PADRE.CATENTRY_ID = CATENTREL.CATENTRY_ID_PARENT)
                 JOIN CATENTDESC AS PADRE_CATENTDESC ON (PADRE_CATENTDESC.CATENTRY_ID = PADRE.CATENTRY_ID AND PADRE_CATENTDESC.LANGUAGE_ID = '-5')
                 JOIN CATGPENREL AS MAESTRO_CATGPENREL ON (MAESTRO_CATGPENREL.CATENTRY_ID = PADRE.CATENTRY_ID AND MAESTRO_CATGPENREL.CATALOG_ID = '10001')
                 JOIN CATGRPREL ON (CATGRPREL.CATGROUP_ID_CHILD = MAESTRO_CATGPENREL.CATGROUP_ID)
                 JOIN CATGROUP AS MAESTRO_CATGROUP2 ON (MAESTRO_CATGPENREL.CATGROUP_ID = MAESTRO_CATGROUP2.CATGROUP_ID)
                 JOIN CATGRPDESC AS MAESTRO_CATGRPDESC2 ON (MAESTRO_CATGROUP2.CATGROUP_ID = MAESTRO_CATGRPDESC2.CATGROUP_ID)
                 JOIN CATGROUP AS MAESTRO_CATGROUP ON (CATGRPREL.CATGROUP_ID_PARENT = MAESTRO_CATGROUP.CATGROUP_ID)
                 JOIN CATGRPDESC AS MAESTRO_CATGRPDESC ON (MAESTRO_CATGROUP.CATGROUP_ID = MAESTRO_CATGRPDESC.CATGROUP_ID)
                 
                 LEFT OUTER JOIN TEMP_RET ON (TEMP_RET.CATENTRY_ID = HIJO.CATENTRY_ID)
                 LEFT OUTER JOIN TEMP_CAT_VTA_HIJO ON (TEMP_CAT_VTA_HIJO.CATENTRY_ID = HIJO.CATENTRY_ID)
                 LEFT OUTER JOIN TEMP_CAT_VTA_PADRE ON (TEMP_CAT_VTA_PADRE.CATENTRY_ID = HIJO.CATENTRY_ID)
                 LEFT OUTER JOIN TEMP_STOCK ON (TEMP_STOCK.CATENTRY_ID = HIJO.CATENTRY_ID)
                 LEFT OUTER JOIN TEMP_CAT_MAESTRO_HIJO ON (TEMP_CAT_MAESTRO_HIJO.CATENTRY_ID = HIJO.CATENTRY_ID)
                 LEFT OUTER JOIN TEMP_PRECIOS AS PRECIOS_HIJO ON (PRECIOS_HIJO.PARTNUMBER = HIJO.PARTNUMBER)
                 LEFT OUTER JOIN TEMP_PRECIOS AS PRECIOS_PADRE ON (PRECIOS_PADRE.PARTNUMBER = PADRE.PARTNUMBER)
                 LEFT OUTER JOIN TEMP_ATTR_DEFINICION ON (TEMP_ATTR_DEFINICION.CATENTRY_ID = HIJO.CATENTRY_ID)
                 WHERE HIJO.MARKFORDELETE = 0
                 AND PADRE.MARKFORDELETE = 0
                 AND CATENTREL.CATRELTYPE_ID = 'PRODUCT_ITEM'
                 
                 ")
productos = fetch(rs, -1)#ESTOS SON LOS PRODUCTOS PUBLICADOS
names(productos) <- c("CATALOGO_MAESTRO_NAME","CATALOGO_MAESTRO2_IDENTIFIER", "SKU_PADRE","NOMBRE_PADRE","MARCA_PADRE","SKU_HIJO","PRECIO_VIGENTE","PRECIO_MASTER","PRECIO_COSTO","IMAGEN")
colnames(productos)
ORDERS <- ORDERS[(ORDERS$PARTNUM %in% productos$SKU_HIJO),] #SACA los productos no publicados de las ordenes



write.table(ORDERS,file="ORDERS.CSV",sep=",",row.names=F)
trans <- read.transactions("ORDERS.CSV", format = "single", sep = ",", cols = c("ORDERS_ID", "PARTNUM"),rm.duplicates = TRUE)
transrules <- apriori(trans, parameter = list(support =0.000001, confidence = 0.000001, maxlen=2,target="rules"))
transrules2 <- as(transrules, "data.frame")

transrules2$rules <- gsub("\\}", "", transrules2$rules)
transrules2$rules <- gsub("\\{", "", transrules2$rules)
transrules2$rules <- as.character(transrules2$rules)
transrules2$antecedent <- sub("=.*$", "\\1", transrules2$rules)
transrules2$antecedent <- substr(transrules2$antecedent, 1, nchar(transrules2$antecedent)-1)
transrules2$consequent <- gsub(".*=>", "", transrules2$rules)
transrules2$consequent <- sub("\\ ","",transrules2$consequent)
transrules2 <- transrules2[which(transrules2$antecedent !="" & transrules2$consequent!=""), ]
transrules2$lift <- as.numeric(transrules2$lift)
transrules2 <- transrules2[order(-transrules2$lift),]
transrules2 <- subset(transrules2,select=c("antecedent","consequent"))
write.csv(transrules2,file="~/Dropbox/ripley/Temp/Dump/public/transrules2.csv",row.names = FALSE)


##############################################################################################################
##############################################################################################################
##############################################################################################################
##############################################################################################################
############################################################################################################








